[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "asgiref==3.6.0",
    "celery==5.3.0",
    "django==4.2",
    "django-cors-headers==3.14.0",
    "djangorestframework==3.14.0",
    "mysqlclient==2.1.1",
    "pillow==10.0.0",
]
