# Generated by Django 4.2 on 2025-05-14 03:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='图片名称', max_length=255)),
                ('description', models.TextField(blank=True, help_text='图片简介')),
                ('image', models.ImageField(help_text='图片文件', upload_to=api.models.get_upload_path)),
                ('width', models.IntegerField(blank=True, editable=False, help_text='图片宽度 (px)', null=True)),
                ('height', models.IntegerField(blank=True, editable=False, help_text='图片高度 (px)', null=True)),
                ('size', models.BigIntegerField(blank=True, editable=False, help_text='图片大小 (bytes)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
