# Generated by Django 4.2 on 2025-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分组名称', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='分组描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='图片所属分组', related_name='images', to='api.group'),
        ),
    ]
