# Generated by Django 4.2 on 2025-05-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_owner'),
    ]

    operations = [
    ]
