# Generated by Django 4.2 on 2025-05-21 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_add_default_layouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='布局名称', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='是否为当前激活的布局')),
                ('config', models.JSONField(default=dict, help_text='布局配置JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'is_active')},
            },
        ),
    ]
