# Generated by Django 4.2 on 2025-05-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_homelayout'),
    ]

    operations = [
    ]
