# Generated by Django 4.2 on 2025-06-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_spacing_to_layouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='会话标识符', max_length=128, unique=True)),
                ('code', models.CharField(help_text='验证码文本', max_length=10)),
                ('image', models.ImageField(help_text='验证码图片', upload_to='captcha/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='过期时间')),
                ('is_used', models.BooleanField(default=False, help_text='是否已使用')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
        migrations.AlterField(
            model_name='homelayout',
            name='config',
            field=models.JSONField(default=dict, help_text='布局配置JSON，包含image_spacing和grid_padding等设置'),
        ),
    ]
